### PR TITLE
Synchronize with OMERO 5.6.9 and update some dependencies

### PR DESCRIPTION
**Pull request by chris-allan**
.

### CODE REVIEW

**Review by sbesson — COMMENTED** [review]
Fairly straightforward dependency bump. Tested against a server configured with LDAP with `-all` as well as `--user USER` and with different log levels. Everything is working as expected.

Do you remember why the `omero.properties` file still needs to be maintained client-side? And is there a particular test scenario associated with it?

**Comment by chris-allan** [comment]
> Do you remember why the omero.properties file still needs to be maintained client-side? And is there a particular test scenario associated with it?

Yes, absolutely. `omero.properties` is only included in a full OMERO.server distribution and consequently not available in any published JARs. If any required default properties are missing, as they were in the last 5.6.4 bump (8d90cd922ae4aa11a01b357b25530618100327cd), Spring beans will fail to initialize. There are no such new properties here since 5.6.4 but I thought it couldn't hurt to update the file. If any one of `--all` or `--user USER` works that's test enough.

**Review by sbesson — APPROVED** [review]

**Comment by sbesson** [comment]
Should we get this out as `0.2.1` or do you have more changes upcoming @chris-allan ?

**Comment by chris-allan** [comment]
I'd like to get #6 in and release as 0.3.0 I think.

**Pull request merged**
